spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: admin
  resources:
    static-locations: classpath:/static
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin
#  kafka:
#    producer:
#      bootstrap-servers: 127.0.0.1:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      bootstrap-servers: 127.0.0.1:9092
server:
  port: 8093
#mq: activemq

